"""empty message

Revision ID: 092d4c27e598
Revises: 51107d39b1d0
Create Date: 2024-06-11 20:53:54.224310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092d4c27e598'
down_revision = '51107d39b1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_table',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_table')
    # ### end Alembic commands ###
