"""Test migration

Revision ID: 316196275e53
Revises: f6a8ddfc0e58
Create Date: 2024-07-24 22:46:41.425411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316196275e53'
down_revision = 'f6a8ddfc0e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###
