"""empty message

Revision ID: 3736c311b078
Revises: 092d4c27e598
Create Date: 2024-06-11 21:01:17.151466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3736c311b078'
down_revision = '092d4c27e598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('num_upcoming_shows')

    # ### end Alembic commands ###
