"""Update show table module

Revision ID: f6a8ddfc0e58
Revises: fac97577587f
Create Date: 2024-07-24 21:58:19.660892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a8ddfc0e58'
down_revision = 'fac97577587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_primary_key('pk_shows', 'show_table', ['id'])
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_constraint('pk_shows', 'shows', type_='primary')
        batch_op.drop_column('shows', 'id')

    # ### end Alembic commands ###
